const EspA = {
    name: ['# 41 Aleix Espargaro'],
    team: 'Aprilia',
    nation: 'Spain',
    points: 63,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/aleix.jpg",
}
const Zarco = {
    name: ['#5 Johann Zarco'],
    team: 'Reale Avintia Ducati',
    nation: 'France',
    points: 30,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0, 
    pic: "images/riderpics/zarco.jpg",   
}
const Dovi = {
    name: ['#04 Andrea Dovizioso'],
    team: 'Ducati Factory',    
    nation: 'Italy',
    points: 269,
    poles: 0,
    wins: 2,
    secondplaces: 3,
    lapsinfirst: 33,
    pic: "images/riderpics/dovi.jpg",
}
const Petrux = {
    name: ['#9 Danilo Petrucci'],
    team: 'Ducati Factory',
    nation: 'Italy',
    points: 176,
    poles: 0,
    wins: 1,
    secondplaces: 0,
    lapsinfirst: 14,
    pic: "images/riderpics/petrux.jpg",
}
const Miller = {
    name: ['#43 Jack Miller'],
    team: 'Primac Ducati',
    nation: 'Australia',
    points: 165,
    poles: 0,
    wins: 2,
    secondplaces: 0,
    lapsinfirst: 2,
    pic: "images/riderpics/miller.jpg",
}
const Pecco = {
    name: ['#63 Francesco Bagnaia'],
    team: 'Primac Ducati',
    nation: 'Italy',
    points: 54,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/pecco.jpg",
}
const Nakagami = {
    name: ['#30 Takaaki Nakagami'],
    team: 'LCR Honda',
    nation: 'Japan',
    points: 74,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/nakagami.jpg",
}
const Crutchlow = {
    name: ['#35 Cal Crutchlow'],
    team: 'LCR Honda',
    nation: 'UK',
    points: 133,
    poles: 0,
    wins: 0,
    secondplaces: 1,
    lapsinfirst: 6,
    pic: "images/riderpics/crutchlow.jpg",
}
const MarA = {
    name: ['#73 Alex Marquez'],
    team: 'Repsol Honda',
    nation: 'Spain',
    points: 0,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/alexm.jpg",
}
const MarM = {
    name: ['#93 Marc Marquez'],
    team: 'Repsol Honda',
    nation: 'Spain',
    points: 420,
    poles: 10,
    wins: 12,
    secondplaces: 6,
    lapsinfirst: 264,
    pic: "images/riderpics/marc.jpg",
}
const Binder = {
    name: ['#33 Brad Binder'],
    team: 'KTM Factory',
    nation: 'South Africa',
    points: 0,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/binder.jpg",
}
const Lecuona = {
    name: ['#27 Iker Lecuona'],
    team: 'KTM Factory',
    nation: 'Spain',
    points: 0,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/lecuona.jpg",
}
const Oliveira = {
    name: ['#88 Miguel Oliveira'],
    team: 'Tech3 KTM',
    nation: 'Portugal',
    points: 33,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/oliveira.jpg",
}
const Mir = {
    name: ['#36 Joan Mir'],
    team: 'Suzuki Factory',
    nation: 'Spain',
    points: 92,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/mir.jpg",
}
const Rins = {
    name: ['#42 Alex Rins'],
    team: 'Suzuki Factory',
    nation: 'Spain',
    points: 205,
    poles: 0,
    wins: 2,
    secondplaces: 1,
    lapsinfirst: 12,
    pic: "images/riderpics/rins.jpg",
}
const Vinales = {
    name: ['#12 Maverick Vinales'],
    team: 'Yamaha Factory',
    nation: 'Spain',
    points: 211,
    poles: 3,
    wins: 2,
    secondplaces: 1,
    lapsinfirst: 49,
    pic: "images/riderpics/vinales.jpg",
}
const Rossi = {
    name: ['#46 Valentino Rossi'],
    team: 'Yamaha Factory',
    nation: 'Italy',
    points: 174,
    poles: 0,
    wins: 0,
    secondplaces: 2,
    lapsinfirst: 11,
    pic: "images/riderpics/rossi.jpg",
}
const Morbidelli = {
    name: ['#21 Franco Morbidelli'],
    team: 'Petronas Yamaha',
    nation: 'Italy',
    points: 115,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/morbidelli.jpg",
}
const Quartararo = {
    name: ['#20 Fabio Quartararo'],
    team: 'Petronas Yamaha',
    nation: 'France',
    points: 192,
    poles: 6,
    wins: 0,
    secondplaces: 5,
    lapsinfirst: 73,
    pic: "images/riderpics/quartararo.jpg",
}
const Pol = {
    name: ['#44 Pol Espargaro'],
    team: 'KTM Factory',
    nation: 'Spain',
    points: 100,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/pol.jpg",
}
const Tito = {
    name: ['#53 Tito Rabat'],
    team: 'Reale Avintia Ducati',
    nation: 'Spain',
    points: 23,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/tito.jpg",
}
const Iannone = {
    name: ['#29 Andrea Iannone'],
    team: 'Aprilia Factory',
    nation: 'Italy',
    points: 43,
    poles: 0,
    wins: 0,
    secondplaces: 0,
    lapsinfirst: 0,
    pic: "images/riderpics/iannone.jpg",
}


